export const LOGO = document.getElementById('logo')
export const LOGINBTN = document.getElementById('login')
export const SUBMITBTN = document.querySelector('.loginForm-submitBtn')
export const GALLERY = document.querySelector('.gallery')
export const EDITIONMODE = document.querySelector('.editionMode')
export const EDITIONBTN = document.querySelector('.editionBtn')
