export const BASEURL = 'http://localhost:5678/api/'

export const LOGO = document.getElementById('logo')
export const LOGINBTN = document.getElementById('login')
export const SUBMITBTN = document.getElementById('loginFormSubmit')
export const GALLERY = document.querySelector('.gallery')
export const EDITIONMODE = document.querySelector('.editionMode')
export const EDITIONBTN = document.querySelector('.editionBtn')
export const MODAL = document.querySelector('.modal')
export const MODALCLOSEBTN = document.querySelector('.modal-close')
export const MODALCONTENT = document.querySelector('.modal-content')
export const MODALGRID = document.querySelector('.gallery-grid')
export const MODALFIRSTVIEW = document.getElementById('modal-first-view')
export const MODALSECONDVIEW = document.getElementById('modal-second-view')
export const DELETEBTN = document.querySelector('.delete-btn')
export const FILTERS = document.querySelector('.filters')
export const ADDPHOTOBTN = document.querySelector('.add-photo')
export const BACKTOMODAL = document.getElementById('back')
